# Azure DevOps pipeline YAML for Bicep deployment

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Replace with your Azure service connection name
  azureSubscription: 'ABR_Sub_Connector'
  location: 'eastus'  # Replace with your desired resource location
  resourceGroup: 'test_rg'
  templateFile: './main.bicep'
  csmParametersFile: './azuredeploy.bicep'

stages:
- stage: Deploy
  jobs:
  - job: BicepDeployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureSubscription: '$(azureSubscription)'
        resourceGroupName: '$(ResourceGroup)'
        location: $(location)
        csmFile: '$(templateFile)'
        csmParametersFile: '$(csmParametersFile'
        deploymentMode: Incremental
        deploymentName: 'DeployPipelineTemplate'