# Azure DevOps pipeline YAML for Bicep deployment

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: BicepDeployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'abr_azure_connection'
        subscriptionId: 'a8ed239b-e5dd-4348-8d82-1d25897ddc12'
        location: 'South India'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://github.com/bharathialwar/bicep-test/blob/main/main.bicep'
        csmParametersFileLink: 'https://github.com/bharathialwar/bicep-test/blob/main/parameters.json'
        deploymentMode: 'Validation'
        deploymentName: 'Bicep Deploy'