# Azure DevOps pipeline YAML for Bicep deployment

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
parameters:
  - name: azureserviceconnection
    type: string
    default: 'ABR_Sub_Connector'

variables:
  location: 'eastus'  
  resourceGroup: 'test_rg'
  templateFile: './main.bicep'
  csmParametersFile: './azuredeploy.bicep'

stages:
- stage: Deploy
  jobs:
  - job: BicepDeployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureSubscription: '${{ parameters.azureServiceConnection}}'
        resourceGroupName: '$(ResourceGroup)'
        location: $(location)
        csmFile: '$(templateFile)'
        csmParametersFile: '$(csmParametersFile'
        deploymentMode: Incremental
        deploymentName: 'DeployPipelineTemplate'