# Azure DevOps pipeline YAML for Bicep deployment

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  # Replace with your Azure service connection name
  azureSubscription: 'ABR_Sub_Connector'
  location: 'eastus'  # Replace with your desired resource location
  resourceGroup: 'test_rg'

stages:
- stage: Deploy
  jobs:
  - job: BicepDeployment
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(azureSubscription)'
        resourceGroupName: '$(ResourceGroup)'
        location: $(location)
        deploymentMode: Incremental
        template: 'bicep-test\main.bicep'
        # Optional: Path to Bicep parameter file (if used)
        # parameterFilePath: 'main.bicepparam'
        # Additional options (refer to task documentation for details)
        # ...