# Azure DevOps pipeline YAML for Bicep deployment

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: BicepDeployment
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy bicep'
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'ABR_Sub_Connector'
        subscriptionId: 'edb04ea6-2dc0-49f0-ba08-d4ff5e2e2fe4'
        location: 'East US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://github.com/bharathialwar/bicep-test/blob/main/main.bicep'
        csmParametersFileLink: 'https://github.com/bharathialwar/bicep-test/blob/main/azuredeploy.bicep'
        deploymentMode: 'Validation'